spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul
    username: minhyeok
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 1024MB   # 파일 하나 최대 1GB
      max-request-size: 1024MB  # 전체 요청 크기 1GB

server:
  port: 8080

file:
  upload-dir: uploads

libreoffice:
  path: "C:/Program Files/LibreOffice/program/soffice.exe"



